server:
  port: 8082

spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/piyu?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  #  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.pipihao.piyu.pojo
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名
    cache-enabled: true

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    com.pipihao.piyu.piyubackground.mapper: DEBUG
  file:
    path: log/myspringboot.log