file:
  uploadPath: D:/img/ #文件上传的路径
  server: http://localhost:81/img/ # 文件服务器地址
server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/piyu?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
#  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.pipihao.piyu.pojo
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true

#mapper:
#  mappers: com.pipihao.piyu.mapper
#  not-empty: false
#  identity: MYSQL

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#showSql Logging是springboot自带的日志组件
#logging:
#  level:
#    com:
#      example:
#        mapper : debug